x-env-bitnami-spark-common:
  &env-bitnami-spark-common

  # security = 0
  SPARK_RPC_AUTHENTICATION_ENABLED: "no"
  SPARK_RPC_ENCRYPTION_ENABLED: "no"
  SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
  SPARK_SSL_ENABLED: "no"

  SPARK_HOME: "/opt/bitnami/spark"
  SPARK_MASTER: "spark://spark-master:7077"
  SPARK_MASTER_HOST: spark-master
  SPARK_MASTER_PORT: 7077
  PYSPARK_PYTHON: "/opt/bitnami/python/bin/python3"

services:
  spark-master:
    image: bitnami/spark
    # image: spark

    environment:
      # SPARK_MODE: master (default)
      <<: *env-bitnami-spark-common

    ports:
      - 8880:8080     # master UI:      host: 8880
      - 18080:18080   # history UI      (resets?)
      - 7077:7077     # master connect  (resets?)
      - 6066:6066     # master REST     (resets?)
      # - 4040:4040     # app UI        (resets?)

  spark-worker:
    image: bitnami/spark

    environment:
      <<: *env-bitnami-spark-common
      SPARK_MODE: worker

    ports:
      - 8081:8081     # worker UI
      # - 4040:4040     # app UI        (resets?)

  jupyter:
    image: tjcelaya/lakehut-notebook
    build: build/jupyter
    ports:
      - "8888:8888"
    user: root
    env_file:
      - path: ".env"
        required: true
    command: start-notebook.py --IdentityProvider.token=''
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./vendor/jupyter/notebook/docs/source/examples:/home/jovyan/work/examples
