---
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000" # API access
      - "9001:9001" # Console access
    volumes:
      - ./data:/data
    environment:
      # defaults for reference
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --address ":9000" --console-address ":9001"