services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8032:8032
    volumes:
      - ./build/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./build/pgadmin/pgadmin-pgpass.txt:/pgadmin-pgpass.txt:ro
    environment:
      PGADMIN_LISTEN_PORT: 8032
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_DEFAULT_SERVER_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy

  redisinsight:
    image: redis/redisinsight
    ports:
      - 5540:5540
    depends_on:
      redis:
        condition: service_healthy
